### ISSUE TITLE
Can not compile x509 using node 12

### ISSUE THREAD

**Issue by maxvanceffer** [fidm/x509#16]
make: *** [x509.target.mk:116: Release/obj.target/x509/src/addon.o] Error 1
make: Leaving directory '/backend/node_modules/x509/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-49-generic
gyp ERR! command "/node/v12.16.2/bin/node" "/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /backend/node_modules/x509
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: x509@0.3.4 (node_modules/x509):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: x509@0.3.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by LucasHillDex** [comment]
Looks like you might've been trying to use the "x509" module rather than the correct @fidm/x509 (this project).
